
import express, { Request, Response } from "express";
import { Pool } from "pg";
import dotenv from "dotenv";
import path from "path"

dotenv.config({path : path.join(process.cwd(), ".env")})

const app = express();
const port = 5000;

app.use(express.json());

// DB: fix HTML entity and remove channel_binding unless explicitly needed
const pool = new Pool({
  connectionString: `${process.env.CONNECTION_STR}`
    
});

const initDB = async () => {
  try {
    // Optional connectivity check
    await pool.query("SELECT 1");

    // USERS TABLE — fixed typos and used TIMESTAMPTZ
    await pool.query(`
      CREATE TABLE IF NOT EXISTS users (
        id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name         VARCHAR(100) NOT NULL,
        email        VARCHAR(150) UNIQUE NOT NULL,
        age          INT,
        phone        VARCHAR(15),
        address      TEXT,
        created_at   TIMESTAMPTZ DEFAULT NOW(),
        updated_at   TIMESTAMPTZ DEFAULT NOW()
      );
    `);

    // TODOS TABLE — fixed typos (title, BOOLEAN), consistent timestamps
    await pool.query(`
      CREATE TABLE IF NOT EXISTS todos (
        id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id      INT REFERENCES users(id) ON DELETE CASCADE,
        title        VARCHAR(200) NOT NULL,
        description  TEXT,
        completed    BOOLEAN DEFAULT false,
        due_date     DATE,
        created_at   TIMESTAMPTZ DEFAULT NOW(),
        updated_at   TIMESTAMPTZ DEFAULT NOW()
      );
    `);

    console.log("✅ Database initialized: users and todos tables are ready.");
  } catch (err) {
    console.error("❌ initDB failed:", err);
    // Optionally fail fast in dev:
    // process.exit(1);
  }
};

initDB();

app.get("/", (req: Request, res: Response) => {
  res.send("Shihabul Islam Alvi");
});

app.post("/users", async (req: Request, res: Response) => {
  const {name , email} = req.body;

 

  try{

    const result = await pool.query(`INSERT INTO users(name , email) VALUES($1 , $2) RETURNING * ` , [name , email]);
    // console.log(result.rows[0]);

  //  res.send({message : " data inserted"})

        res.status(500).json({
        success : false,
        message : "Data Inserted Successfully",
        data : result.rows[0],
    

    })

  }catch(err : any){
    res.status(500).json({
        success : false,
        message : err.message,
    })
  }



  res.status(201).json({
    success: true,
    message: "Api is working",
  });
});

app.listen(port, () => {
  console.log(`Example app listening on port ${port}`);
});
