import express, { Request, Response } from "express";
import { Pool } from "pg";
import dotenv from "dotenv";
import path from "path";

dotenv.config({ path: path.join(process.cwd(), ".env") });

const app = express();
const port = Number(process.env.PORT ?? 5000);

app.use(express.json());

const pool = new Pool({ connectionString: process.env.CONNECTION_STR });

const initDB = async () => {
  try {
    await pool.query("SELECT 1");

    await pool.query(`
      CREATE TABLE IF NOT EXISTS users (
        id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name         VARCHAR(100) NOT NULL,
        email        VARCHAR(150) UNIQUE NOT NULL,
        age          INT,
        phone        VARCHAR(15),
        address      TEXT,
        created_at   TIMESTAMPTZ DEFAULT NOW(),
        updated_at   TIMESTAMPTZ DEFAULT NOW()
      );
    `);

    await pool.query(`
      CREATE TABLE IF NOT EXISTS todos (
        id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id      INT REFERENCES users(id) ON DELETE CASCADE,
        title        VARCHAR(200) NOT NULL,
        description  TEXT,
        completed    BOOLEAN DEFAULT false,
        due_date     DATE,
        created_at   TIMESTAMPTZ DEFAULT NOW(),
        updated_at   TIMESTAMPTZ DEFAULT NOW()
      );
    `);

    console.log("✅ Database initialized: users and todos tables are ready.");
  } catch (err) {
    console.error("❌ initDB failed:", err);
  }
};

initDB();

app.get("/", (_req: Request, res: Response) => {
  res.send("Shihabul Islam Alvi");
});

// Create user  POST 
app.post("/users", async (req: Request, res: Response) => {
  const { name, email } = req.body;

  if (!name || !email) {
    return res.status(400).json({ success: false, message: "name and email are required" });
  }

  try {
    const result = await pool.query(
      `INSERT INTO users(name, email) VALUES($1, $2) RETURNING *`,
      [name, email]
    );

    return res.status(201).json({ success: true, message: "Data inserted successfully", data: result.rows[0] });
  } catch (err: any) {
    return res.status(500).json({ success: false, message: err.message });
  }
});

// Get all users
app.get("/users", async (_req: Request, res: Response) => {
  try {
    const result = await pool.query(`SELECT * FROM users`);
    return res.status(200).json({ success: true, message: "Users retrieved successfully", data: result.rows });
  } catch (err: any) {
    return res.status(500).json({ success: false, message: err.message, details: err });
  }
});

// Get user by id
app.get("/users/:id", async (req: Request, res: Response) => {
  const idParam = req.params.id;
  if (!idParam) return res.status(400).json({ success: false, message: "Invalid id" });

  const id = parseInt(idParam, 10);
  if (Number.isNaN(id)) return res.status(400).json({ success: false, message: "Invalid id" });

  try {
    const result = await pool.query(`SELECT * FROM users WHERE id = $1`, [id]);
    if (result.rowCount === 0) return res.status(404).json({ success: false, message: "User not found" });
    return res.status(200).json({ success: true, data: result.rows[0] });
  } catch (err: any) {
    return res.status(500).json({ success: false, message: err.message });
  }
});


// UPDATE

app.put("/users/:id", async (req: Request, res: Response) => {
  // console.log(req.params.id);
  const { name, email } = req.body;
  try {
    const result = await pool.query(
      `UPDATE users SET name=$1, email=$2 WHERE id=$3 RETURNING *`,
      [name, email, req.params.id]
    );

    if (result.rows.length === 0) {
      res.status(404).json({
        success: false,
        message: "User not found",
      });
    } else {
      res.status(200).json({
        success: true,
        message: "User updated successfully",
        data: result.rows[0],
      });
    }
  } catch (err: any) {
    res.status(500).json({
      success: false,
      message: err.message,
    });
  }
});


// Delete Method

app.delete("/users/:id", async (req: Request, res: Response) => {
  // console.log(req.params.id);
  try {
    const result = await pool.query(`DELETE FROM users WHERE id = $1`, [
      req.params.id,
    ]);

    if (result.rowCount === 0) {
      res.status(404).json({
        success: false,
        message: "User not found",
      });
    } else {
      res.status(200).json({
        success: true,
        message: "User deleted successfully",
        data: result.rows,
      });
    }
  } catch (err: any) {
    res.status(500).json({
      success: false,
      message: err.message,
    });
  }
});



// todos crud
app.post("/todos", async (req: Request, res: Response) => {
  const { user_id, title } = req.body;

  try {
    const result = await pool.query(
      `INSERT INTO todos(user_id, title) VALUES($1, $2) RETURNING *`,
      [user_id, title]
    );
    res.status(201).json({
      success: true,
      message: "Todo created",
      data: result.rows[0],
    });
  } catch (err: any) {
    res.status(500).json({
      success: false,
      message: err.message,
    });
  }
});

app.get("/todos", async (req: Request, res: Response) => {
  try {
    const result = await pool.query(`SELECT * FROM todos`);

    res.status(200).json({
      success: true,
      message: "todos retrieved successfully",
      data: result.rows,
    });
  } catch (err: any) {
    res.status(500).json({
      success: false,
      message: err.message,
      datails: err,
    });
  }
});

app.use((req, res) => {
  res.status(404).json({
    success: false,
    message: "Route not found",
    path: req.path,
  });
});




app.listen(port, () => console.log(`Example app listening on port ${port}`));
